#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
# SPDX-License-Identifier: Apache-2.0
"""Every source file carries the SPDX line; this proves it and can add it.

One line rather than a header block: `SPDX-License-Identifier: Apache-2.0` is
machine-readable, survives reformatting, and does not push the actual code below
a screen of boilerplate. The check is a closed set over tracked source files so
a new file cannot land unlicensed; `--fix` inserts the line after a shebang or
PEP 723 script block where one exists, at the top otherwise.

The set is every extension in COMMENT, not just `.rs` and `.py`. The original
gate covered those two and nothing else, which left the eight `.mjs` Node test
files, the example's `.sh`, and the conformance `.tf` permanently unlicensed —
the same extension blindness issue #32 was about, one layer up: a closed set is
only closed over what it enumerates. `.ts`, `.astro` and `.css` are in it for the
same reason, and each one taught the inserter something a leader alone cannot
express: an Astro component's `---` fence must stay the first line, and `//` in
CSS is not a comment but an invalid declaration a parser recovers from by eating
the rule that follows it.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

SPDX = "SPDX-License-Identifier: Apache-2.0"

#: Extension -> comment leader. What is deliberately absent: `.md` (prose, and
#: the line would render), `.json` (no comment syntax), `.toml`/`.yml` (config
#: read by tools that surface every line to a reader; the licensing signal
#: belongs on code). `.pyi` is generated by scripts/generate-py-stubs.py, which
#: writes the line itself; it is in the set so the generator cannot silently
#: stop doing that.
COMMENT = {
    ".rs": "//",
    ".py": "#",
    ".pyi": "#",
    ".mjs": "//",
    ".ts": "//",
    ".astro": "//",
    ".css": "/*",
    ".sh": "#",
    ".tf": "#",
}

#: Extension -> comment closer, for the syntaxes a leader alone cannot express.
#: CSS is the one that matters: `//` is not a comment there at all but an invalid
#: declaration, and a parser recovers from it by skipping to the next semicolon —
#: which silently eats the declaration that follows. A leader-only map would emit
#: a header that removes a rule.
CLOSER = {".css": " */"}

#: Files that must always be in the enumerated set. An empty set is caught by
#: the floor in `main`; these catch a set that isn't empty but came from the
#: wrong place (a working directory outside the repo, a checkout of something
#: else). This script and the core crate root are files no refactor removes. A
#: pathspec that stops matching one extension is the per-extension floor's job,
#: because a sentinel only covers its own extension.
SENTINELS = (Path("scripts/check-license-headers.py"), Path("microvms-core/src/lib.rs"))


def tracked_sources() -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", *(f"*{ext}" for ext in COMMENT)],
        capture_output=True,
        text=True,
        check=True,
    )
    return [Path(line) for line in out.stdout.splitlines() if line]


def has_spdx(path: Path) -> bool:
    # The line must appear near the top: a mention buried in a doc later in the
    # file is documentation, not a license declaration.
    head = "\n".join(path.read_text(encoding="utf-8").splitlines()[:12])
    return SPDX in head


def insertion_point(lines: list[str], path: Path) -> int:
    """After a shebang, a PEP 723 block, or an Astro frontmatter fence."""
    at = 0
    if lines and lines[0].startswith("#!"):
        at = 1
    if (
        path.suffix == ".py"
        and at < len(lines)
        and lines[at].startswith("# /// script")
    ):
        while at < len(lines) and lines[at] != "# ///":
            at += 1
        at += 1  # past the closing marker
    # An `.astro` component's `---` fence must be the first line in the file, so
    # the header goes inside it — where the language is JavaScript and `//` holds.
    # Inserting above the fence turns the component's script into page content.
    if path.suffix == ".astro" and lines and lines[0].strip() == "---":
        at = 1
    return at


def fix(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    at = insertion_point(lines, path)
    lines.insert(at, f"{COMMENT[path.suffix]} {SPDX}{CLOSER.get(path.suffix, '')}")
    # An empty file has no trailing newline to preserve; copying that absence
    # onto the line just inserted writes an unterminated last line (measured as
    # ruff W292 when this same gate was ported to another repo).
    keep_bare = bool(text) and not text.endswith("\n")
    path.write_text("\n".join(lines) + ("" if keep_bare else "\n"), encoding="utf-8")


def main() -> int:
    apply = "--fix" in sys.argv[1:]
    sources = tracked_sources()
    # A check over nothing reports nothing, and that used to read as a pass:
    # "all 0 tracked source files carry the SPDX line", exit 0.
    if not sources:
        print(
            "license headers: `git ls-files` returned no tracked source files for"
            f" {', '.join(f'*{ext}' for ext in COMMENT)}; run this from the repo root"
        )
        return 1
    absent = [str(s) for s in SENTINELS if s not in sources]
    if absent:
        print(
            f"license headers: `git ls-files` returned {len(sources)} files without"
            f" {', '.join(absent)}, which this repo always tracks; the enumerator"
            " read the wrong tree"
        )
        return 1
    # Every extension in COMMENT is there because this tree tracks files of that
    # kind, so each must yield at least one. Without this, a pathspec that lost
    # `*.mjs` would pass with the Node files unchecked, and the two sentinels
    # above, a `.py` and a `.rs`, would never notice.
    bare = [ext for ext in COMMENT if not any(s.suffix == ext for s in sources)]
    if bare:
        print(
            f"license headers: `git ls-files` returned {len(sources)} files but none"
            f" ending in {', '.join(bare)}; either the pathspec stopped matching or"
            " the tree no longer has that kind of file, and then COMMENT should drop it"
        )
        return 1
    missing = [p for p in sources if not has_spdx(p)]
    if not missing:
        print(
            f"license headers: all {len(sources)} tracked source files carry the SPDX line"
        )
        return 0
    if apply:
        for path in missing:
            fix(path)
        print(f"license headers: added the SPDX line to {len(missing)} files")
        return 0
    print(f"license headers: {len(missing)} files are missing '{SPDX}':")
    for path in missing:
        print(f"  {path}")
    print("run scripts/check-license-headers.py --fix")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
